var searchData=
[
  ['scheduling_20tests_44327',['Scheduling Tests',['../group__kernel__sched__tests.html',1,'']]],
  ['semaphore_44328',['Semaphore',['../group__kernel__sys__events__tests.html',1,'(Global Namespace)'],['../group__kernel__sys__sem__tests.html',1,'(Global Namespace)']]],
  ['semaphore_20apis_44329',['Semaphore APIs',['../group__semaphore__apis.html',1,'']]],
  ['semaphore_20tracing_20apis_44330',['Semaphore Tracing APIs',['../group__subsys__tracing__apis__sem.html',1,'']]],
  ['sensor_20interface_44331',['Sensor Interface',['../group__sensor__interface.html',1,'']]],
  ['service_20discovery_20protocol_20_28sdp_29_44332',['Service Discovery Protocol (SDP)',['../group__bt__sdp.html',1,'']]],
  ['settings_44333',['Settings',['../group__settings.html',1,'']]],
  ['settings_20backend_20interface_44334',['Settings backend interface',['../group__settings__backend.html',1,'']]],
  ['settings_20name_20processing_44335',['Settings name processing',['../group__settings__name__proc.html',1,'']]],
  ['settings_20subsystem_20runtime_44336',['Settings subsystem runtime',['../group__settings__rt.html',1,'']]],
  ['shared_20multi_2dheap_20interface_44337',['Shared multi-heap interface',['../group__shared__multi__heap.html',1,'']]],
  ['shell_20api_44338',['Shell API',['../group__shell__api.html',1,'']]],
  ['single_20mmio_20region_20macros_44339',['Single MMIO region macros',['../group__device-mmio-single.html',1,'']]],
  ['single_2dlinked_20list_44340',['Single-linked list',['../group__single-linked-list__apis.html',1,'']]],
  ['sleep_20tests_44341',['Sleep Tests',['../group__kernel__sleep__tests.html',1,'']]],
  ['smp_20tests_44342',['SMP Tests',['../group__kernel__smp__integration__tests.html',1,'(Global Namespace)'],['../group__kernel__smp__module__tests.html',1,'(Global Namespace)'],['../group__kernel__smp__tests.html',1,'(Global Namespace)']]],
  ['sntp_44343',['SNTP',['../group__sntp.html',1,'']]],
  ['socket_20options_20for_20tls_44344',['Socket options for TLS',['../group__secure__sockets__options.html',1,'']]],
  ['spi_20emulation_20interface_44345',['SPI Emulation Interface',['../group__spi__emul__interface.html',1,'']]],
  ['spi_20interface_44346',['SPI Interface',['../group__spi__interface.html',1,'']]],
  ['spinlock_20apis_44347',['Spinlock APIs',['../group__spinlock__apis.html',1,'']]],
  ['spinlock_20tests_44348',['Spinlock Tests',['../group__kernel__spinlock__tests.html',1,'']]],
  ['stack_20apis_44349',['Stack APIs',['../group__stack__apis.html',1,'']]],
  ['stack_20tracing_20apis_44350',['Stack Tracing APIs',['../group__subsys__tracing__apis__stack.html',1,'']]],
  ['stacks_44351',['Stacks',['../group__kernel__stack__tests.html',1,'']]],
  ['states_44352',['States',['../group__subsys__pm__states.html',1,'']]],
  ['stream_20to_20flash_20interface_44353',['Stream to flash interface',['../group__stream__flash.html',1,'']]],
  ['structured_20data_44354',['Structured Data',['../group__structured__data.html',1,'']]],
  ['subnet_20configuration_44355',['Subnet Configuration',['../group__bt__mesh__cfg__subnet.html',1,'']]],
  ['subsystems_44356',['Subsystems',['../group__subsys.html',1,'']]],
  ['syscall_20tracing_20apis_44357',['Syscall Tracing APIs',['../group__subsys__tracing__apis__syscall.html',1,'']]],
  ['syscon_20interface_44358',['SYSCON Interface',['../group__syscon__interface.html',1,'']]],
  ['system_44359',['System',['../group__subsys__pm__sys.html',1,'']]],
  ['system_20pm_20tracing_20apis_44360',['System PM Tracing APIs',['../group__subsys__tracing__apis__pm__system.html',1,'']]]
];
